flowchart TD
    T[test/] -->  F[unit/]
    T[test/] -->  G[integration/]
    T[test/] -->  H[e2e/]

    F-->C[application/]
    F-->B[domain/]
    F-->D[infrastructure/]

    %% SRC
    style T fill:#6630d4,stroke:#6630d4,stroke-width:2px,color:#ffffff

    %% Domain Layer Style
    style B fill:#fce0a9,stroke:#db865c,stroke-width:3px,color:#db865c

    %% Application Layer Style
    style C fill:#fca9ce,stroke:#d1639a,stroke-width:3px,color:#d1639a

    %% Infrastructure Layer Style
    style D fill:#aaebfc,stroke:#2cb3cb,stroke-width:3px,color:#2cb3cb